---
services:
  chrome:
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
      - --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb
    container_name: chrome
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped

  meilisearch:
    container_name: meilisearch
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    image: getmeili/meilisearch:v1.6
    restart: unless-stopped
    volumes:
      - ./.data/meili_data:/meili_data

  web:
    container_name: hoarder-web
    env_file:
      - .env
    environment:
      DATA_DIR: /hoarder/data
      MEILI_ADDR: http://meilisearch:7700
      REDIS_HOST: valkey
    image: ghcr.io/hoarder-app/hoarder-web:release
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./.data/hoarder/data:/hoarder/data

  workers:
    container_name: hoarder-workers
    depends_on:
      web:
        condition: service_started
    env_file:
      - .env
    environment:
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /hoarder/data
      MEILI_ADDR: http://meilisearch:7700
      REDIS_HOST: http://valkey:6379
      # OPENAI_API_KEY: ...
    image: ghcr.io/hoarder-app/hoarder-workers:release
    restart: unless-stopped
    volumes:
      - ./.data/hoarder/data:/hoarder/data
