---
name: PostgreSQL
services:
  postgres:
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: homelab
      POSTGRES_USER: postgres-homelab
      TZ: Asia/Kolkata
    image: postgres:16-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - ./.data/var/lib/postgresql:/var/lib/postgresql
      - ./.data/var/lib/postgresql/data:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d
