name: pgAdmin4
services:
  pgadmin4:
    container_name: pgadmin4
    env_file:
      - .env
    hostname: pgadmin4
    image: dpage/pgadmin4
    ports:
      - 5050:80
      - 5051:443
    restart: unless-stopped
    volumes:
      - pgadmin4:/var/lib/pgadmin
volumes:
  pgadmin4:
    driver: rclone
    driver_opts:
      allow_other: "true"
      poll_interval: 0
      remote: pcloud-homelab-data:pgadmin4/var/lib/pgadmin
      vfs_cache_mode: full
