---
name: pgAdmin4
services:
  pgadmin4:
    container_name: pgadmin4
    env_file:
      - .env
    image: dpage/pgadmin4
    ports:
      - 5050:80
      - 5051:443
    restart: unless-stopped
    volumes:
      - ./.data/var/lib/pgadmin:/var/lib/pgadmin
