services:
  backup-sync:
    command: |
      sh -c 'while true; do
        cp -ru /source/* /destination/;
        sleep 3600;
      done'
    depends_on:
      - gamevault-db-backup
    image: alpine:latest
    volumes:
      - db-backups:/source:ro
      - gamevault-backup:/destination
  gamevault-backend:
    container_name: gamevault-backend
    depends_on:
      - gamevault-db
    environment:
      DB_HOST: gamevault-db
      DB_PASSWORD: gamevault
      DB_USERNAME: gamevault
    hostname: gamevault-backend
    image: phalcode/gamevault-backend:latest
    ports:
      - 8080:8080/tcp
    restart: unless-stopped
    volumes:
      - source: gamevault
        target: /files
        type: volume
        volume:
          nocopy: true
          subpath: files
      - source: gamevault
        target: /media
        type: volume
        volume:
          nocopy: true
          subpath: media
  gamevault-db:
    container_name: gamevault-db
    environment:
      POSTGRES_DB: gamevault
      POSTGRES_PASSWORD: gamevault
      POSTGRES_USER: gamevault
    hostname: gamevault-db
    image: postgres:16
    restart: unless-stopped
    volumes:
      - ./.data/var/lib/postgresql/data:/var/lib/postgresql/data
      - db-backups:/backups

  gamevault-db-backup:
    command: |
      bash -c 'while true; do
        sleep 300;
        pg_dump -Fc > /backups/gamevault_$$(date +%Y%m%d_%H%M%S).dump;
        find /backups -type f -mtime +7 -delete;
        sleep 86400;
      done'
    depends_on:
      - gamevault-db
    environment:
      PGHOST: gamevault-db
      POSTGRES_DB: gamevault
      POSTGRES_PASSWORD: gamevault
      POSTGRES_USER: gamevault
    image: postgres:16
    volumes:
      - db-backups:/backups

volumes:
  gamevault-backup:
    driver: rclone
    driver_opts:
      allow_other: "true"
      poll_interval: 0
      remote: pcloud-homelab-data:backups/gamevault
      vfs_cache_mode: full
  db-backups:
  gamevault:
    driver: rclone
    driver_opts:
      allow_other: "true"
      poll_interval: 0
      remote: pcloud-homelab-data:gamevault
      vfs_cache_mode: full
