name: PostgreSQL
services:
  postgres:
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: homelab
      POSTGRES_USER: postgres-homelab
      TZ: Asia/Kolkata
    image: postgres:16-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - ./.data/var/lib/postgresql:/var/lib/postgresql
      - ./.data/var/lib/postgresql/data:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d
  valkey:
    container_name: valkey
    healthcheck:
      interval: 1s
      retries: 5
      test:
        - CMD-SHELL
        - redis-cli ping | grep PONG
      timeout: 3s
    hostname: valkey
    image: valkey/valkey:alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      # - ./valkey.conf:/etc/valkey/valkey.conf
      - ./.data/data:/data
