services:
  cosmos-server:
    container_name: cosmos-server
    environment:
      TZ: Australia/Melbourne
    hostname: cosmos-server
    image: azukaar/cosmos-server:latest
    network_mode: host
    privileged: true
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /:/mnt/host
      - ./.data/config:/config
