services:
  stirling-pdf:
    container_name: stirling-pdf
    # volumes:
    # - ./.data/trainingData:/usr/share/tessdata # Required for extra OCR languages
    # - ./.data/extraConfigs:/configs
    #      - ./customFiles:/customFiles/
    #      - ./logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_GB
    hostname: stirling-pdf
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    ports:
      - 8090:8080
