services:
  valkey:
    container_name: valkey
    healthcheck:
      interval: 1s
      retries: 5
      test:
        - CMD-SHELL
        - redis-cli ping | grep PONG
      timeout: 3s
    hostname: valkey
    image: valkey/valkey:alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      # - ./valkey.conf:/etc/valkey/valkey.conf
      - ./.data/data:/data
