services:
  chrome:
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
      - --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb
    container_name: chrome
    hostname: chrome
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
  meilisearch:
    container_name: meilisearch
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    hostname: meilisearch
    image: getmeili/meilisearch:v1.13.3
    restart: unless-stopped
    volumes:
      - source: meilisearch
        target: /meili_data/
        type: volume
        volume:
          nocopy: true
          subpath: meili_data/
  web:
    container_name: karakeep
    env_file:
      - .env
    environment:
      BROWSER_WEB_URL: http://chrome:9222
      # OPENAI_API_KEY: ...

      # You almost never want to change the value of the DATA_DIR variable.
      # If you want to mount a custom directory, change the volume mapping above instead.
      DATA_DIR: /data # DON'T CHANGE THIS
      MEILI_ADDR: http://meilisearch:7700
    hostname: karakeep
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      # By default, the data is stored in a docker volume called "data".
      # If you want to mount a custom directory, change the volume mapping to:
      # - /path/to/your/directory:/data
      - source: karakeep
        target: /data/
        type: volume
        volume:
          nocopy: true
          subpath: data/

volumes:
  karakeep:
    driver: rclone
    driver_opts:
      allow_other: "true"
      poll_interval: 0
      remote: pcloud-homelab-data:karakeep
      vfs_cache_mode: full
  meilisearch:
    driver: rclone
    driver_opts:
      allow_other: "true"
      poll_interval: 0
      remote: pcloud-homelab-data:meilisearch
      vfs_cache_mode: full
