services:
  app:
    container_name: nginx-proxy-manager
    hostname: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    ports:
      - 80:80
      - 81:81
      - 443:443
    restart: unless-stopped
    volumes:
      - ./.data/data:/data
      - ./.data/etc/letsencrypt:/etc/letsencrypt
